### ISSUE TITLE
Fix openedx-webhooks staging

### ISSUE THREAD

**Issue by feanil** [openedx/openedx-webhooks#203]
openedx-webhooks-staging is throwing an exception when receiving a PR webhook. Debug the issue and fix it so that we can use stage for testing again.

```
2022-10-04T15:54:44.946309+00:00 app[worker.1]: [2022-10-04 15:54:44,945: ERROR/ForkPoolWorker-8] openedx_webhooks.tasks.github.pull_request_changed_task[3a301fdd-0d04-4e03-bef8-a85f6c87af97]: Couldn't pull_request_changed_task
2022-10-04T15:54:44.946341+00:00 app[worker.1]: Traceback (most recent call last):
2022-10-04T15:54:44.946349+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/github.py", line 34, in pull_request_changed_task
2022-10-04T15:54:44.946349+00:00 app[worker.1]: ret = pull_request_changed(pull_request)
2022-10-04T15:54:44.946349+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/github.py", line 71, in pull_request_changed
2022-10-04T15:54:44.946350+00:00 app[worker.1]: fixer.fix()
2022-10-04T15:54:44.946352+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 374, in fix
2022-10-04T15:54:44.946353+00:00 app[worker.1]: self.fix_ospr()
2022-10-04T15:54:44.946353+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 422, in fix_ospr
2022-10-04T15:54:44.946353+00:00 app[worker.1]: self._make_jira_issue()
2022-10-04T15:54:44.946354+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 482, in _make_jira_issue
2022-10-04T15:54:44.946354+00:00 app[worker.1]: new_issue = self.actions.create_ospr_issue(
2022-10-04T15:54:44.946354+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 799, in create_ospr_issue
2022-10-04T15:54:44.946355+00:00 app[worker.1]: custom_fields = get_jira_custom_fields(get_jira_session())
2022-10-04T15:54:44.946355+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/cachetools/func.py", line 62, in wrapper
2022-10-04T15:54:44.946356+00:00 app[worker.1]: v = func(*args, **kwargs)
2022-10-04T15:54:44.946356+00:00 app[worker.1]: File "/app/openedx_webhooks/utils.py", line 301, in get_jira_custom_fields
2022-10-04T15:54:44.946356+00:00 app[worker.1]: field_resp.raise_for_status()
2022-10-04T15:54:44.946356+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/requests/models.py", line 1022, in raise_for_status
2022-10-04T15:54:44.946357+00:00 app[worker.1]: raise HTTPError(http_error_msg, response=self)
2022-10-04T15:54:44.946357+00:00 app[worker.1]: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nosuchserver.atlassian.net/rest/api/2/field
2022-10-04T15:54:44.959753+00:00 app[worker.1]: [2022-10-04 15:54:44,959: INFO/ForkPoolWorker-8] Task openedx_webhooks.tasks.github.pull_request_changed_task[3a301fdd-0d04-4e03-bef8-a85f6c87af97] succeeded in 2.5614383260253817s: 'Traceback (most recent call last):
2022-10-04T15:54:44.959754+00:00 app[worker.1]: File "/app/openedx_webhooks/__init__.py", line 95, in __call__
2022-10-04T15:54:44.959755+00:00 app[worker.1]: return self.run(*args, **kwargs)
2022-10-04T15:54:44.959755+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/github.py", line 34, in pull_request_changed_task
2022-10-04T15:54:44.959756+00:00 app[worker.1]: ret = pull_request_changed(pull_request)
2022-10-04T15:54:44.959756+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/github.py", line 71, in pull_request_changed
2022-10-04T15:54:44.959756+00:00 app[worker.1]: fixer.fix()
2022-10-04T15:54:44.959757+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 374, in fix
2022-10-04T15:54:44.959758+00:00 app[worker.1]: self.fix_ospr()
2022-10-04T15:54:44.959758+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 422, in fix_ospr
2022-10-04T15:54:44.959758+00:00 app[worker.1]: self._make_jira_issue()
2022-10-04T15:54:44.959759+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 482, in _make_jira_issue
2022-10-04T15:54:44.959759+00:00 app[worker.1]: new_issue = self.actions.create_ospr_issue(
2022-10-04T15:54:44.959759+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 799, in create_ospr_issue
2022-10-04T15:54:44.959760+00:00 app[worker.1]: custom_fields = get_jira_custom_fields(get_jira_session())
2022-10-04T15:54:44.959760+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/cachetools/func.py", line 62, in wrapper
2022-10-04T15:54:44.959760+00:00 app[worker.1]: v = func(*args, **kwargs)
2022-10-04T15:54:44.959761+00:00 app[worker.1]: File "/app/openedx_webhooks/utils.py", line 301, in...'
```

Reproducing the error: 
* `heroku logs --tail -a openedx-webhooks-staging`
* Edit the title of https://github.com/nedbat/webhook-testing/pull/121
* See the exception occur.

**Comment by feanil** [comment]
This blocks deploying https://github.com/openedx/openedx-webhooks/issues/201 so picking this up now.

**Comment by feanil** [comment]
Looks like the Jira settings for stage have a fake server.  Looking at the code, it looks like if the setting doesn't exist, it will just disable the Jira portion of the code which seems like a better choice for this.  I've saved the `JIRA_OAUTH_CONSUMER_KEY`, `JIRA_OAUTH_RSA_KEY`, `JIRA_SERVER` and `JIRA_USERNAME` locally and I'm gonna try to remove them from the staging system to see if resolves the issue.

Looks like in production, the `JIRA_SERVER` setting is an empty string but the other settings are still set.  So much more of this might need to be cleaned up.

**Comment by feanil** [comment]
@nedbat you might have some context on this. Should we remove the JIRA related keys from staging and production openedx-webhooks for now?  Or is there a plan to connect these to 2U Jira at some point?

**Comment by feanil** [comment]
Removing the JIRA related settings has resolved the issue in staging.   If we're not using them in production, we should probably unset the other JIRA values in production as well.

**Comment by feanil** [comment]
Closing this since the staging issue is resolved.

**Comment by nedbat** [comment]
Sorry about that, the empty server name was used in prod as the way to stop trying to talk to Jira while we didn't have credentials.  I am still working on getting credentials.  Definitely changing all the settings to empty strings is a good way to go.

**Comment by feanil** [comment]
Done, I've emptied the strings in prod.
