### ISSUE TITLE
Openedx-webhooks graphql is deprecated and needs to be updated

### ISSUE THREAD

**Issue by feanil** [openedx/openedx-webhooks#212]
The projects Graphql Endpoint we're using looks like it's no longer supported and we need to update to the new v2 api for all our graphql queries.

```
2022-11-02T14:41:46.627901+00:00 app[worker.1]: [2022-11-02 14:41:46,627: ERROR/ForkPoolWorker-8] openedx_webhooks.tasks.github.pull_request_changed_task[5e9d5b86-626f-4508-a139-40cc18626b4a]: Couldn't pull_request_changed_task
2022-11-02T14:41:46.627918+00:00 app[worker.1]: Traceback (most recent call last):
2022-11-02T14:41:46.627919+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/github.py", line 34, in pull_request_changed_task
2022-11-02T14:41:46.627919+00:00 app[worker.1]: ret = pull_request_changed(pull_request)
2022-11-02T14:41:46.627920+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/github.py", line 69, in pull_request_changed
2022-11-02T14:41:46.627920+00:00 app[worker.1]: current = current_support_state(pr)
2022-11-02T14:41:46.627920+00:00 app[worker.1]: File "/app/openedx_webhooks/tasks/pr_tracking.py", line 221, in current_support_state
2022-11-02T14:41:46.627921+00:00 app[worker.1]: current.github_projects = set(pull_request_projects(pr))
2022-11-02T14:41:46.627921+00:00 app[worker.1]: File "/app/openedx_webhooks/gh_projects.py", line 54, in pull_request_projects
2022-11-02T14:41:46.627922+00:00 app[worker.1]: data = graphql_query(query=PROJECTS_FOR_PR, variables=variables)
2022-11-02T14:41:46.627922+00:00 app[worker.1]: File "/app/openedx_webhooks/utils.py", line 243, in graphql_query
2022-11-02T14:41:46.627923+00:00 app[worker.1]: raise Exception(f"GraphQL error: {returned!r}")
2022-11-02T14:41:46.627925+00:00 app[worker.1]: Exception: GraphQL error: {'data': {'repository': {'pullRequest': None}}, 'errors': [{'type': 'NOT_FOUND', 'path': ['repository', 'pullRequest', 'projectNextItems'], 'locations': [{'line': 8, 'column': 7}], 'message': 'The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.'}]}
```

**Comment by feanil** [comment]
https://github.com/openedx/openedx-webhooks/pull/211 should fix the issue but we may also want to put in some sort of gaurd around the graphql since that API is less reliable than the Rest API.
